[area]
[area.Antarctica]
short_name = "AN"
lat = [-60, -90]
lon = [-180, 180]


[variable]
variables = [
    "2m_temperature",
    "surface_pressure",
    "total_precipitation",
    "ice_temperature_layer_1",
    "ice_temperature_layer_2",
    "ice_temperature_layer_3",
    "ice_temperature_layer_4",
    "snow_depth",
    "snowfall",
    "snowmelt",
    "temperature_of_snow_layer",
]

[time]
years = [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
